export enum MimeType {
  Csv = 'text/csv',
  Gif = 'image/gif',
  Glb = 'model/gltf-binary',
  Hls = 'application/x-mpegURL',
  Html = 'text/html',
  Jpeg = 'image/jpeg',
  Js = 'text/javascript',
  Json = 'application/json',
  Mov = 'video/quicktime',
  Mp4 = 'video/mp4',
  Webm = 'video/webm',
  Pdf = 'application/pdf',
  Png = 'image/png',
  Text = 'text/plain',
  Usdz = 'model/vnd.usdz+zip',
  Zip = 'application/zip',
  Webp = 'image/webp',
  Heic = 'image/heic',
}
