export enum WebhookHeader {
  AccessToken = 'X-Shopify-Access-Token',
  Hmac = 'X-Shopify-Hmac-Sha256',
  Topic = 'X-Shopify-Topic',
  Domain = 'X-Shopify-Shop-Domain',
}

export type Topic =
  | 'app/uninstalled'
  | 'carts/create'
  | 'carts/update'
  | 'checkouts/create'
  | 'checkouts/delete'
  | 'checkouts/update'
  | 'collection_listings/add'
  | 'collection_listings/remove'
  | 'collection_listings/update'
  | 'collections/create'
  | 'collections/delete'
  | 'collections/update'
  | 'customer_groups/create'
  | 'customer_groups/delete'
  | 'customer_groups/update'
  | 'customers/create'
  | 'customers/delete'
  | 'customers/disable'
  | 'customers/enable'
  | 'customers/update'
  | 'draft_orders/create'
  | 'draft_orders/delete'
  | 'draft_orders/update'
  | 'fulfillment_events/create'
  | 'fulfillment_events/delete'
  | 'fulfillments/create'
  | 'fulfillments/update'
  | 'order_transactions/create'
  | 'orders/cancelled'
  | 'orders/create'
  | 'orders/delete'
  | 'orders/fulfilled'
  | 'orders/paid'
  | 'orders/partially_fulfilled'
  | 'orders/updated'
  | 'product_listings/add'
  | 'product_listings/remove'
  | 'product_listings/update'
  | 'products/create'
  | 'products/delete'
  | 'products/update'
  | 'refunds/create'
  | 'shop/update'
  | 'themes/create'
  | 'themes/delete'
  | 'themes/publish'
  | 'themes/update'
  | 'inventory_levels/connect'
  | 'inventory_levels/update'
  | 'inventory_levels/disconnect'
  | 'inventory_items/create'
  | 'inventory_items/update'
  | 'inventory_items/delete'
  | 'locations/create'
  | 'locations/update'
  | 'locations/delete';
