import { Options } from 'yargs';
import { Options as CommonOptions } from './common';
export interface Argv extends CommonOptions {
    _: string[];
    vendorDll?: boolean;
    npm?: boolean;
    cache?: boolean;
    assets?: boolean;
    graphql?: boolean;
}
export declare const command = "clean";
export declare const desc = "deletes files generated by sewing-kit";
export declare const aliases: string[];
export declare const builder: {
    [key: string]: Options;
};
export declare function handler(argv: Argv): Promise<void>;
