import {existsSync, readdirSync} from 'fs';
import {resolve, join} from 'path';

import {Compiler} from 'webpack';

export interface Options {
  basePath: string;
  assetPrefix?: string;
  host?: string;
  port?: number;
  proxy?: boolean;
}

export enum Entrypoint {
  Client = 'client',
  Server = 'server',
  Error = 'error',
}

export const HEADER = `
  // Generated by @shopify/react-server/webpack-plugin
`;

export function noSourceExists(
  entry: Entrypoint,
  options: Options,
  {options: {context = ''}}: Compiler,
) {
  const {basePath: path} = options;
  const basePath = resolve(context, path);

  // if there is a folder we assume it has an index file
  if (existsSync(join(basePath, entry))) {
    return false;
  }

  // otherwise we look for explicit files in the folder
  const dirFiles = readdirSync(basePath);
  const filenameRegex = new RegExp(`^${entry}.[jt]sx?$`);
  return dirFiles.find(file => filenameRegex.test(file)) == null;
}
