# This file strictly follows the rules defined in the Ruby style guide:
#   http://shopify.github.io/ruby-style-guide/
# Before updating anything please sync-up with #ruby-style-guide on Slack.
inherit_gem:
  rubocop-shopify: rubocop.yml

AllCops:
  TargetRubyVersion: 2.6.3
  Exclude:
    - 'node_modules/**/*'
    - 'test/**/node_modules/**/*'
    - 'vendor/**/*'
    - '*.gemspec'

Metrics/PerceivedComplexity:
  Max: 6
  Exclude:
    - bin/**/*

Metrics/CyclomaticComplexity:
  Max: 6
  Exclude:
    - bin/**/*

Metrics/ModuleLength:
  CountComments: true
  Max: 100

Metrics/AbcSize:
  Max: 25

Metrics/BlockLength:
  CountComments: true
  Max: 5
  Exclude:
    - lib/**/*.rake
    - test/**/*
    - bin/**/*
    - Gemfile
    - config/initializers/**/*
    - config/environments/**/*

Metrics/ClassLength:
  CountComments: true
  Max: 100
  Exclude:
    - test/**/*

Naming/MethodName:
  Exclude:
    - test/**/*

Style/ClassAndModuleChildren:
  Enabled: false

Layout/LineLength:
  Max: 120
  Exclude:
    - Guardfile
    - Gemfile
    - config/**/*
    - bin/**/*

Style/MethodCallWithArgsParentheses:
  Exclude:
    - bin/**/*

Style/PerlBackrefs:
  Exclude:
    - bin/**/*

Style/SpecialGlobalVars:
  Exclude:
    - bin/**/*
