name: quilt-rails
up:
  - ruby: 3.1.2
  - bundler

commands:
  test: bundle exec rake test
  lint: bundle exec rubocop
  format: bundle exec rubocop --auto-correct
  cop:
    run: bundle exec rubocop -F --auto-correct
