name: react-server
up:
  - ruby: 2.6.3
  - bundler
  - node:
      version: v12.14.0
      yarn: v1.22.5

commands:
  test: bundle exec rake test
  lint: bundle exec rubocop --fail-fast
  format: bundle exec rubocop --auto-correct
  cop:
    run: bundle exec rubocop -F --auto-correct
