# frozen_string_literal: true

require 'bundler/gem_tasks'

begin
  require 'bundler/setup'
rescue LoadError
  puts 'You must `gem install bundler` and `bundle install` to run rake tasks'
end

APP_RAKEFILE = File.expand_path("test/dummy/Rakefile", __dir__)
load 'rails/tasks/engine.rake'

Bundler::GemHelper.install_tasks

require 'rake/testtask'

Rake::TestTask.new do |t|
  t.libs << 'test'
  t.pattern = 'test/**/*_test.rb'
end

Rake::TestTask.new do |t|
  t.libs << 'test'
  t.name = 'test:unit'
  t.pattern = 'test/quilt_rails/**/*_test.rb'
end

require 'rake/testtask'

task default: :test
